pipeline:
  name: remote-inputs
  identifier: remoteinputs
  projectIdentifier: shauryaTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: new_docker_test
                    image: alpine
                    shell: Sh
                    command: echo node --version
                    envVariables: <+input>
                  description: ec
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.CItestK8sConnectorrqe3ef2W3n
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: accountsk
        repoName: goHelloWorldServer
        build: <+input>
