pipeline:
  name: remote-inputs
  identifier: remoteinputs
  projectIdentifier: shauryaTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: new_docker_test
                    image: alpine
                    shell: Sh
                    command: |-
                      echo node --version
                      exit 1
                    envVariables: <+input>
                  description: ec
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: accountsk
        repoName: goHelloWorldServer
        build: <+input>
