pipeline:
  identifier: Build_shaurya_harness_goHelloWorldServer_1709891168851
  name: Build goHelloWorldServer
  orgIdentifier: default
  projectIdentifier: shauryatesting
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: <+input>
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    connectorRef: <+input>
                    image: <+input>
                    shell: Sh
                    command: go build
                    privileged: true
                    outputVariables:
                      - name: name
                      - name: test
                      - name: forSecret
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestcoverage
                  name: go_test_coverage
                  spec:
                    shell: Sh
                    command: go test -coverprofile=coverage.out ./...
                    outputVariables:
                      - name: testvaraaaa
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestreport
                  name: go_test_report
                  spec:
                    command: "export GOBIN=/home/harness/go/bin\n\t\texport PATH=/home/harness/go/bin:$PATH\n\t\techo $PATH\n\t\tgo install github.com/jstemmer/go-junit-report/v2@latest\n\t\tgo test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml"
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      password: <+input>
                      repo: hello/world
                      tags: latest
                      username: <+input>
                  timeout: ""
                  type: Plugin
              - step:
                  name: rw
                  identifier: rw
                  template:
                    templateRef: run
                    versionLabel: "1"
                    templateInputs:
                      type: Run
                      spec:
                        connectorRef: <+input>
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: <+input>
                    image: <+input>
                    shell: Sh
                    command: echo "12344"
                    imagePullPolicy: Always
                    resources:
                      limits:
                        memory: 1000Mi
                        cpu: 400m
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
