pipeline:
  name: Build goHelloWorldServer
  identifier: Build_goHelloWorldServer_1700482781093
  projectIdentifier: onboardingflowtest
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: <+input>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.oauthsk
        repoName: shaurya-harness/goHelloWorldServer
        build: <+input>
