pipeline:
  name: Build goHelloWorldServer
  identifier: Build_goHelloWorldServer_1683714896027
  projectIdentifier: default
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8test
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: shaurya-harness/goHelloWorldServer
        build: <+input>
