pipeline:
  name: Build goHelloWorldServer
  identifier: Build_goHelloWorldServer_1699553215593
  projectIdentifier: shauryatesting
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: skgithubaccount
        repoName: goHelloWorldServer
        build: <+input>
